// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rafflingState.sql

package database

import (
	"context"
)

const getRaffleState = `-- name: GetRaffleState :one
SELECT has_raffled FROM rafflingState
`

func (q *Queries) GetRaffleState(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getRaffleState)
	var has_raffled bool
	err := row.Scan(&has_raffled)
	return has_raffled, err
}

const updateRaffleState = `-- name: UpdateRaffleState :exec
UPDATE rafflingState SET has_raffled = $1
`

func (q *Queries) UpdateRaffleState(ctx context.Context, hasRaffled bool) error {
	_, err := q.db.Exec(ctx, updateRaffleState, hasRaffled)
	return err
}
