// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: totalMinted.sql

package database

import (
	"context"
)

const getTotalMinted = `-- name: GetTotalMinted :one
SELECT total_nfts_minted FROM totalMinted
`

func (q *Queries) GetTotalMinted(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, getTotalMinted)
	var total_nfts_minted int16
	err := row.Scan(&total_nfts_minted)
	return total_nfts_minted, err
}

const updateTotalNftsMinted = `-- name: UpdateTotalNftsMinted :exec
UPDATE totalMinted SET total_nfts_minted = $1
`

func (q *Queries) UpdateTotalNftsMinted(ctx context.Context, totalNftsMinted int16) error {
	_, err := q.db.Exec(ctx, updateTotalNftsMinted, totalNftsMinted)
	return err
}
