// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: whitelistMinters.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWhitelistMinter = `-- name: CreateWhitelistMinter :exec
INSERT INTO whitelistMinters(discord_id, wallet_address, nonce, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWhitelistMinterParams struct {
	DiscordID     string
	WalletAddress pgtype.Text
	Nonce         int16
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) CreateWhitelistMinter(ctx context.Context, arg CreateWhitelistMinterParams) error {
	_, err := q.db.Exec(ctx, createWhitelistMinter,
		arg.DiscordID,
		arg.WalletAddress,
		arg.Nonce,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getWhitelistMinterById = `-- name: GetWhitelistMinterById :one
SELECT discord_id, wallet_address, nonce, created_at, updated_at FROM whitelistMinters
WHERE discord_id = $1
`

func (q *Queries) GetWhitelistMinterById(ctx context.Context, discordID string) (Whitelistminter, error) {
	row := q.db.QueryRow(ctx, getWhitelistMinterById, discordID)
	var i Whitelistminter
	err := row.Scan(
		&i.DiscordID,
		&i.WalletAddress,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
